### ISSUE TITLE
Can I use something like "hidden-sm-down"?

### ISSUE THREAD

**Issue by johnunclesam** [freshbooks/ember-responsive#100]
In Bootstrap and other css libraries I can use something like "hidden-sm-down" or maybe "media-breakpoint-up(md)".

How can I do with this library in Ember?

**Comment by k-fish** [comment]
This addon includes a property `classNames` on the `media` service. You can add it to hbs to accomplish what you want I believe.

```hbs
<div class="{{media.classNames}}">
...
</div>
```
