### ISSUE TITLE
memory leak in test run

### ISSUE THREAD

**Issue by lmcardle** [freshbooks/ember-responsive#101]
I am debugging a memory leak we are dealing with which we run into when running out test suite. So far I have tacked the issue to this library. Unfortunately I have not yet identified the exact cause. Has anyone come across a similar issue? The one area of code that looks suspicious is the following lines within the media.js file:

```
if (matcher.addListener) {
  matcher.addListener(function(matcher){
    Ember.run(null, listener, matcher);
  });
}
```

My suspicion is that listeners are being added to the window and never being destroyed after each test run. Any thoughts?

**Comment by lmcardle** [comment]
I just confirmed that this is the cause of the memory leak in the test run. If I change these lines to the following, the memory leak goes away:

```
let config = Ember.getOwner(this).resolveRegistration('config:environment');
let isTestEnv = config.environment === 'test';
if (matcher.addListener && !isTestEnv) {
  matcher.addListener(function(matcher){
    Ember.run(null, listener, matcher);
  });
}
```

**Comment by k-fish** [comment]
The cause is likely the listener not being removed and subsequent tests firing all previously bound listeners. See discussion to the PR #103
