### ISSUE TITLE
Media binding issue

### ISSUE THREAD

**Issue by stevetyler** [freshbooks/ember-responsive#104]
I'm trying to send a webkit message that's either true or false binding to media.isMobile. I've tried using a CP but that doesn't work. I've got it working below using an observer on media.classNames and media.isMobile was intermittent for some reason. I've also had to use the same code on init. If there's a better way to do this please let me know. Thanks

`sendWebkitMessage: observer('media.classNames', function() {
    if (this.get('media.isMobile')) {
      try {
        console.log('send webkit message true');
        window.webkit.messageHandlers.shouldShowSidebarButton.postMessage(true);
      }
      catch(err) {}
    }`

**Comment by k-fish** [comment]
The `is<Class>` properties are set when `mql` or `window.matchMedia` listeners fire (https://github.com/freshbooks/ember-responsive/blob/master/addon/media.js#L174).

It's been brought up that the matching should emit events to be consumed; this would likely be the ideal strategy. In the meantime, another option is to override the `match` function in the service locally to duplicate existing functionality, but in addition to this, include a check to send your `postMessage` if it matches on mobile.

**Comment by stevetyler** [comment]
Ok thanks for this. I'm having problems overriding the service and I've created a local service in app/media/service.js and then `import Media from 'ember-responsive/addon/media'; ` but I'm getting 'could not find module 'ember-responsive''. Any advice appreciated. Thanks

**Comment by stevetyler** [comment]
It didn't like Pods so I refactored and it all works now. Many thanks
