### ISSUE TITLE
Computed property to change variable

### ISSUE THREAD

**Issue by jrock2004** [freshbooks/ember-responsive#110]
So I am trying to write some code that watches `media.isMobile` and then updated the view. Here is my twiddle

https://ember-twiddle.com/a907e9e648e6f9fd862cd504fc73b719?openFiles=controllers.application.js%2C

**Comment by k-fish** [comment]
Can you elaborate on this issue?

I need more context to understand what you're asking. The issue tracker is for bugs with the repo, if this is a help question, you can ask in `#-help` on Ember slack (you can @ me there)

**Comment by k-fish** [comment]
Haven't heard back? I'm going to close this but feel free to respond with comments or join the Ember slack.
