### ISSUE TITLE
Component Property reset on resize (shrink width only)

### ISSUE THREAD

**Issue by fran-worley** [freshbooks/ember-responsive#111]
Can you think of a reason why my component property is reset when resizing the window?

It only happens when making the window smaller and has only started happening since I added some conditional code to change the html used on mobile devices. If I remove ember-responsive from this component, my property stays intact on resize.

I've tried watching the component Lifecycle Hooks, but it doesn't appear that the component is being re-rendered (which would have explained the property reset).

I just wondered whether you could think of anything that might be causing this to point me in the right direction for de-bugging!

**Comment by fran-worley** [comment]
If it helps, I'm manually injecting the media service into my component (rather than using the initialiser approach) and this is the extend of ember resize code in my component:

```handlebars
{{#if media.isMobile}}
  <!-- Write some html specific to mobile devices here -->
{{else}}
  <!-- Write some html specific to larger devices here -->
{{/if}}
```

**Comment by k-fish** [comment]
Which component property are you having trouble with? The media `isMobile` property in your _if_ condition should only change the content rendered inside the component, unless you are rendering components with two-way bindings and the child components are modifying the parent value?

**Comment by fran-worley** [comment]
@k-fish thanks for coming back to me. 

The property that empties is called `documents` and is an Ember Array of Ember Data Models. We fetch these when the component is initialised, but for some reason on resize the array seems to empty. As I said before, if I remove ember resize from the component, my documents remain on resize.

This is a slightly more detailed example of the component in question:
```handlebars
{{#if media.isMobile}}
  {{#each documents as |document|}}
    <!-- Render a simple mobile friendly component with the document-->
  {{/each}}
{{else}}
  <!-- Render a table component with the documents -->
{{/if}}
```

**Comment by k-fish** [comment]
Hmm. I'm still having a bit of trouble figuring out how this addon would be emptying your array. Do you mean the array of items isn't rendered or that the array in javascript turns into `[]`?

Ember responsive simply provides a conditional; When `media.isMobile` is `true` (you are on a mobile breakpoint), it will show `Render a simple mobile friendly component with the document`. If you resize to desktop, it will rerender with `Render a table component with the documents`. When resizing the components inside your `if` block will be created/destroyed based on the changing conditional.

**Comment by fran-worley** [comment]
The array populates fine in both states (isMobile and not mobile).
When resizing the browser smaller past the point where isMobile returns false the array empties. 
However if you load the component at a size when isMobile returns true and scale the page up the property stays populated.

**Comment by fran-worley** [comment]
Your explanation is exactly what I assumed was happening. I'm guessing that it's probably a leaky component that has raised its head through use of the isMobile conditional. Happy to conclude this is an issue with my app and not the library thanks for pointing me in the right direction and for a great Lib!
