### ISSUE TITLE
Deprecation warning under ember 2.18

### ISSUE THREAD

**Issue by bartocc** [freshbooks/ember-responsive#117]
## Version

2.0.5

## How to reproduce

`git clone https://github.com/bartocc/ember-2.18.2-barebone.git`
`cd ember-2.18.2-barebone`
`yarn install`
`ember install ember-responsive@2.0.5`

## Actual result

You should see the following deprecation message

```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/julien/Projects/ember-2.18.2-barebone/node_modules/ember-getowner-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
```

## Expected result

No deprecation message

**Comment by k-fish** [comment]
Closing for now. See related PR.
