### ISSUE TITLE
`media` helper doesn't respond to window resizes

### ISSUE THREAD

**Issue by samselikoff** [freshbooks/ember-responsive#125]
It seems the `media` helper doesn't respond to window resizes. I'm trying out something like this:

```hbs
{{#if (media 'isDesktop')}}
  ...
{{else}}
```

It works if I refresh the app, but if I go from desktop to mobile, it doesn't update. Is this expected behavior? If so, I think we should not encourage using the helper (and instead use the service).

**Comment by k-fish** [comment]
Not expected behaviour. Thanks for taking a look. I'll update the helper.

**Comment by k-fish** [comment]
Added a PR that should address this issue, take a look.

**Comment by samselikoff** [comment]
nice! works 👍
