### ISSUE TITLE
Helper in 3.X beta does not work correctly in app

### ISSUE THREAD

**Issue by erichonkanen** [freshbooks/ember-responsive#130]
Hello, I just upgraded to the beta and am getting an issue where:

- `if (media 'isDesktop')` does not work in my app but DOES work in an integration test.
- `if (media 'desktop')` does work in my app but dot NOT work in integration test.

Not sure if I'm doing anything wrong but that's what I found :D

**Comment by erichonkanen** [comment]
I got around it by doing this which makes me think that when I render the component in the integration test it doesnt have a default media set? using `await setBreakpoint('desktop')` did not work either.

```
  test('it renders for authenticated user', async function(assert) {
    // hack to get around ember-responsive test issue.
    // https://github.com/freshbooks/ember-responsive/issues/130
    this.owner.lookup('service:media').set('desktop', true);

    await render(hbs`{{global-navigation}}`);
```

**Comment by k-fish** [comment]
I checked it out and `if (media 'isDesktop')` should be working as intended, are you sure the breakpoint is matching? The default breakpoint includes `jumbo` as the largest size, which might be the cause of your problem (large screens will match with `isJumbo` instead of `isDesktop`).

**Comment by erichonkanen** [comment]
that could have been it! I reverted back to my default breakpoints that use `isXs isSm isMd isLg isXl` since changing them would require a more involved approach for me... I'll try again later :D
