### ISSUE TITLE
Usage in Engine Addon

### ISSUE THREAD

**Issue by roberkules** [freshbooks/ember-responsive#134]
hi,

just came across an issue when using in an engine, I defined my own set of breakpoints in the main app, but the engine still used the default set of breakpoints. after an aha moment I figured it out, the "media" service must be shared (as a dependent service) with the engine app, otherwise the media service would be initialized twice (inside the engine with the default breakpoints)

```javascript
const Eng = Engine.extend({
  modulePrefix,
  podModulePrefix,
  Resolver,
  dependencies: {
    services: [
      'media',
      ...
    ],
  },
});
```

maybe worth mentioning in the usage guide.

**Comment by k-fish** [comment]
Hey @roberkules, thanks for mentioning it. I'll put up a PR quick if you'd like to take a look (I don't use engines regularly).

**Comment by roberkules** [comment]
added my comment over there.

anyways, thanks!

**Comment by k-fish** [comment]
You added a comment? I can't see it?

**Comment by roberkules** [comment]
my bad (first time giving feedback on a PR on github)

**Comment by k-fish** [comment]
Closing, thanks for the issue / PR
