### ISSUE TITLE
v3 Final?

### ISSUE THREAD

**Issue by jherdman** [freshbooks/ember-responsive#137]
Hi friends!

I was wondering if v3 final is on the horizon? I'd love access to test helpers that work with the new testing style, but I'm a bit cautious about putting a beta release into production. Is there anything I can do to help?

**Comment by k-fish** [comment]
Hey @jherdman,

v3 proper is pretty close, I've been waiting for addon users to come back with issues (which is indeed the case) before finalizing v3. My understanding is that a fair amount of people are still migrating to the new qunit and test helpers, but the issues coming in have slowed down so probably just a couple weeks of smooth sailing away from mainlining it. If any major issues pop up, I always appreciate the help.

**Comment by acorncom** [comment]
@k-fish any updates here? so far it doesn't look like there have been that many problems reported ...

**Comment by k-fish** [comment]
Yup, updating it now. https://github.com/freshbooks/ember-responsive/pull/139

**Comment by k-fish** [comment]
Updated. Give it a shot.
