### ISSUE TITLE
v3.0.0 is missing from the changelog

### ISSUE THREAD

**Issue by Turbo87** [freshbooks/ember-responsive#140]
https://github.com/freshbooks/ember-responsive/blob/1e8d7b1daea09b859e5f2c888858eccae0e63a27/CHANGELOG.md exists, but it does not seem to contain any information on the current v3.0.0 release(s). Is there information available somewhere on what has changed since the last documented release?

**Comment by k-fish** [comment]
Changes were listed in the release notes and in the README under 'upgrading to 3.x', but I forgot to update the changelog. Fixed now (see #141). I'll reopen if you have additional concerns.
