### ISSUE TITLE
call this._super(...arguments) when overriding init method

### ISSUE THREAD

**Issue by nightire** [freshbooks/ember-responsive#144]
ember 3.11.0-beta will not tolerate overriding init method without calling `this._super(...arguments)`, below will cause application break down:

https://github.com/freshbooks/ember-responsive/blob/613f89e35c88b2809ac3941a4dff01924e0083d6/addon/services/media.js#L123-L138

**Comment by ryanto** [comment]
👍 Just started seeing this as well in travis.

**Comment by ryanto** [comment]
PR here: https://github.com/freshbooks/ember-responsive/pull/145

**Comment by k-fish** [comment]
See #145
