### ISSUE TITLE
Old and new syntax

### ISSUE THREAD

**Issue by olenderhub** [freshbooks/ember-responsive#147]
is it possible to do somehow old and new syntax in different files? (for example 1/10 tests using new test syntax and rest use old syntax). We are upgrading the new test style in the whole application, but there are a lot of changes in the whole project which is a nightmare to fix and merge all at once.

**Comment by k-fish** [comment]
Which syntax are you having trouble porting? Acceptance syntax should be the same, integration test syntax changed from
```js
setBreakpointForIntegrationTest(this, 'mobile');
```
to
```js
setBreakpoint('mobile');
```

The integration tests should be a find/replace `setBreakpointForIntegrationTest(this` -> `setBreakpoint(`.

**Comment by olenderhub** [comment]
Both syntax for integration and acceptance tests. Let's assume that I want to have half tests with old syntax (`moduleForAcceptance`) and a half with the new syntax (`module('Acceptance:..`):

So I will have:

```
import { setBreakpoint } from 'ember-responsive/test-support';
```

and other tests would use:

```
import './responsive'; // You need to import helpers to use them in your tests.
```

For now, I create a custom solution which I installed version 3.0.0 and copied + modified files from 2.0.8 so now I have it locally. I am closing this issue because created a custom solution). If there is any better option for it which I don't see, please let me know. Thank you.

**Comment by k-fish** [comment]
That would have been my suggestion, make a custom helper that is forwards/backwards compatible. :+1:
