### ISSUE TITLE
Overlapping breakpoints don't function in tests as they do in the site

### ISSUE THREAD

**Issue by jhitchins88** [freshbooks/ember-responsive#154]
If you define your breakpoints to overlap, testing does not work as it does in the site.

Example, if your `breakpoints.js` file looks like this:

```
export default {
  tablet-or-larger:  '(min-width: 768px)',
  desktop-or-larger: '(min-width: 992px)',
  jumbo:   '(min-width: 1201px)'
};
```

You can have your template look like this and work in the site.

```
{{if (media 'desktopOrLarger') "I'm a larger screen" "I'm not a larger screen"}}
```

However, in tests, you cannot set multiple breakpoints.  Something like `setBreakpoint('jumbo')` does not set `desktop-or-larger`, and there's no other way to set multiple viewports or the size directly to match multiple viewports.

**Comment by jhitchins88** [comment]
My proposal is to change `setBreakpoint` to accept an array, allowing multiple mocked breakpoints.  This lets the user define what breakpoints they want. E.g. `setBreakpoint(['desktop-or-larger', 'jumbo'])` would work for the above example.  Alternatively, we can have a separate function like `setMultipleBreakpoints(` so there's no confusion.

I wrote up a quick and dirty `setBreakpoint` that accepts arrays, and it seems to work well enough.

**Comment by k-fish** [comment]
Yeah that sounds fairly reasonable, I'm surprised we haven't run into this before :thinking:. Would you be willing to put a PR?

**Comment by jhitchins88** [comment]
Sure.  I'll work something up.
