### ISSUE TITLE
Make injection key configurable

### ISSUE THREAD

**Issue by mphasize** [freshbooks/ember-responsive#16]
Hi, 

I just began using ember-responsive in one of my projects and it looks great so far.
However, there's one issue I came across: My project is using models with an attribute named `media` which conflicts with the default injection of ember-responsive.

Looking at ember-responsive.js I think it shouldn't be too difficult to make the `media` key used in the injections configurable. Either as part of the initializer or maybe as a config variable before.

Just a first idea:

    App.responsive( {
        options: {
          injectAs: "media",
          classPrefix: "media"
        },
    	media: {
    		mobile: '(max-width: 768px)',
    		tablet: '(min-width: 769px) and (max-width: 1024px)',
    		desktop: '(min-width: 1025px) and (max-width: 1280px)',
    		jumbo: '(min-width: 1281px)',
    	}
    } );

Where `injectAs` could be used to configure `this.get('media')` and `classPrefix` could be used to configure the css classes prefix `media-[breakpoint]`.

Any thoughts on this? If you think this should be part of ember-responsive and if you agree that this is a good approach, I could probably supply a pull request.

Cheers!
Marcus

**Comment by k-fish** [comment]
Please refer to the linked PR (explained in the readMe), thanks.
