### ISSUE TITLE
Show support for 'prefers-color-scheme'

### ISSUE THREAD

**Issue by mminkoff** [freshbooks/ember-responsive#206]
The following media queries work already, and provide opportunities for some additional styling.  Perhaps worth adding to the Getting Started section of the README?

```
dark: '(prefers-color-scheme: dark)',
light: '(prefers-color-scheme: light)'
```

**Comment by k-fish** [comment]
That's a good call, as long as we are explicit about it being something you can also do due to `matchMedia` and not something explicitly supported (all our tests and terminology are based on responsiveness). If you want to put up a PR I'd be happy to merge it :smile:

**Comment by mminkoff** [comment]
I recognize that there's a context issue.  I'd still call this responsiveness, just as I'd say orientation is responsiveness, but putting either in the "breakpoints" file doesn't quite fit.  Perhaps something to consider for the future.  Having two different add-ons that run media queries doesn't make much sense.

I'll try to put together a PR.

**Comment by k-fish** [comment]
@mminkoff yeah it's probably a matter of interpretation. I'd agree it's important enough to have it as a note in the README to help others. For the addon to actively support it, I think it should at least have a test, so if you want to figure out a way to test it with testem/qunit ( ` --force-dark-mode`?:thinking:) a PR for that would be welcome as well :smile:

**Comment by k-fish** [comment]
Closed by https://github.com/freshbooks/ember-responsive/pull/208
