### ISSUE TITLE
Build failing. Is this project still alive?

### ISSUE THREAD

**Issue by albertodiazdorado** [freshbooks/ember-responsive#265]
It looks very promising for making ember applications responsive, but the last commit happened 7 months ago and, most importantly, the build is failing.

Am I safe to use this package or should I consider other options?

**Comment by alexBaizeau** [comment]
Hey yes, it's still alive, FreshBooks made it private by mistake and then public again and we lost all of our stars.

**Comment by albertodiazdorado** [comment]
Hi @alexBaizeau , I am not worried about stars, but about red builds :(

**Comment by alexBaizeau** [comment]
Ok, Makes sense, the project is still alive, but really stable. Feel free to contribute to fix the build.

**Comment by k-fish** [comment]
Should be fixed in #267, thanks for making an issue :tada:. As @alexBaizeau mentioned it's fairly stable so unless there is a feature that needs to be added we don't check in very often.

**Comment by k-fish** [comment]
Let us know if you have any additional questions, either here or via new issue. Closing for now.

**Comment by albertodiazdorado** [comment]
Thank you very much for the help @alexBaizeau and @k-fish ! :D
