### ISSUE TITLE
Support ability to bind responsive class names to <body> tag

### ISSUE THREAD

**Issue by f3ndot** [freshbooks/ember-responsive#29]
There are a few use cases, design-wise, where we need the responsive classes available on the `body` tag (e.g. Drop.js's DOM binding is a child of the body). Ember Responsive should support the ability or, by default, bind the class names to the body tag.

Currently a (hacky) workaround can be performed in the app using `ember-responsive` by creating an initializer:

``` js
// app/initializers/ember-responsive-body-class-names.js
import Ember from 'ember';

/*
* Make the Ember Responsive className apply to the <body>
* tag
*
*/
export default {
  name : 'emberResponsiveBodyClassNames',
  initialize: function() {
    Ember.Route.reopen({
      updateBodyClassNames: function() {
        this._super();

        var classNames = Ember.$('body').attr('class');
        Ember.$('body').attr('class', classNames.replace(/\s*media-.[a-zA-Z-_\.]+\s*/g, ''));
        Ember.$('body').addClass(this.get('media.classNames'));
      }.on('init').observes('media.classNames')
    });
  }
};
```

**Comment by emoryy** [comment]
I'd just like to note that with this workaround the observer will (unnecessarily) run with each and every route    instance. It's far enough to put the observer once into the application route.
It's also needless to call `this._super()`, since this is our observer, there is no super implementation for it.

So the application route would be like this:
```javascript
import Ember from 'ember';

export default Ember.Route.extend({

  updateBodyClassNames: Ember.on('init', Ember.observer('media.classNames', function() {
    const body = Ember.$('body');
    const classNames = body.attr('class');
    if (classNames) {
      body.attr('class', classNames.replace(/\s*media-.[a-zA-Z-_\.]+\s*/g, ''));
    }
    body.addClass(this.get('media.classNames'));
  })),

});
```

**Comment by k-fish** [comment]
Ember has changed a fair amount since this was proposed, and there are addons to address this kind of issue (https://github.com/ef4/ember-set-body-class). Closing 😃
