### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by mikejerome** [freshbooks/ember-responsive#31]
In the README.md it says to get started just "npm install ember-responsive" but I actually had to use "ember install ember-responsive" to get it work using ember-cli 0.2.3

**Comment by JKGisMe** [comment]
+1, i was confused about why it didn't tell me to `ember install ember-responsive` so i just did it anyway

**Comment by FutoRicky** [comment]
https://github.com/freshbooks/ember-responsive/pull/43
