### ISSUE TITLE
CP's are not firing on version 4.0.0

### ISSUE THREAD

**Issue by rreckonerr** [freshbooks/ember-responsive#338]
Computed properties are not recomputed on media change.

Reproduction: https://github.com/freshbooks/ember-responsive/pull/339

**Comment by rreckonerr** [comment]
Any updates on this? Looks like an ember.js related issue, right?

**Comment by amauryt** [comment]
I had this very issue while upgrading ember-responsive on my app (Ember v3.22). The fix from @rreckonerr seems good to me. Could it be possible to have a new release with this fix?

**Comment by gzurbach** [comment]
Hello there! I confirm this is also happening in my app running Ember 3.16. When would we get a patched version? 

Thanks a lot for all the good work! 👏

**Comment by knownasilya** [comment]
I think the values need to use https://api.emberjs.com/ember/release/functions/@ember%2Fobject%2Fcompat/dependentKeyCompat

**Comment by knownasilya** [comment]
Yes please 👍🏼

**Comment by rreckonerr** [comment]
@jali-clarke Hi! Tagging you as someone who was the last to merge any changes to master :)
Is there any chance you could take a look at the proposed fix? This prevents me from upgrading to the latest version of the addon,

**Comment by jali-clarke** [comment]
hi @rreckonerr, the changes I made were administrative / tooling-related; I don't have any context into anything happening here.  lemme bring this to the attention of the code owners 👍

**Comment by rreckonerr** [comment]
Thank you! Would really appreciate it 👍

**Comment by jali-clarke** [comment]
hey again @rreckonerr - we're transitioning a new team to own this repo and they'll be taking a look next week if that's alright.  let me know if you have any questions
