### ISSUE TITLE
Greater Then/Less Then Comparison

### ISSUE THREAD

**Issue by knownasilya** [freshbooks/ember-responsive#38]
Instead of doing something like

```js
greaterThanMobile: computed('media.isTablet', 'media.isDesktop', 'media.isJumbo', {
  get() {
    var isTablet = this.get('media.isTablet');
    var isDesktop = this.get('media.isDekstop');
    var isJumbo = this.get('media.isJumbo');

    return isTablet || isDesktop || isJumbo;
  }
})
```

Doing something like `greaterThanMobile: computed.gt('media.mobile')`.

**Comment by mitchlloyd** [comment]
Just thought I would point out that properties like `greaterThanMobile` are a natural fit for the media query API. You could probably configure a breakpoint like this:

```javascript
export default {
  greaterThanMobile:  '(min-width: 769px)'
};
```

**Comment by knownasilya** [comment]
Ah, good point.

**Comment by k-fish** [comment]
The media query api solution mentioned above is a good one.
