### ISSUE TITLE
React to changes without observers

### ISSUE THREAD

**Issue by jeremytm** [freshbooks/ember-responsive#44]
With [ember observers being highly discouraged](https://www.youtube.com/watch?v=vvZEddrClAQ), I wonder if you could provide a way to programmatically react to changes within `media`.

I wrote to Stefan from the talk above and referred to this library in particular.
His response:
> Typically when I make such libs, I provide properties (for reading and computed properties to depend on) but if users must respond programmatically, I provide a events. Or sometimes more specialized callbacks.

Maybe a way for us to register a listener to the `media` object?

**Comment by k-fish** [comment]
I think the implementation of this would rely on window resize events, so at best this ember-responsive would just include a resize addon (like `ember-resize`) and send specific events once it determined the new breakpoint.

I think it's just as easy, and less overhead to let the user decide whether they want resize events or not, and just include something for resize events themselves.

Something like:
```js
this.get('resizeService').on('resize', () => { this.get('media.isMobile') ... etc });
```
