### ISSUE TITLE
Deprecation warning with Ember v2.1.0

### ISSUE THREAD

**Issue by charlatan154** [freshbooks/ember-responsive#45]
`DEPRECATION: The `initialize` method for Application initializer 'responsive' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.`

**Comment by alexBaizeau** [comment]
Hi, ember-responsive 1.2.1 has been released today and it should address that deprecation.

**Comment by charlatan154** [comment]
Hi, i keep getting this deprecation warning even with v1.2.1. As i can see addon's initializer has still two arguments, which triggers the deprecation warning.

**Comment by jeremytm** [comment]
+1

**Comment by alexBaizeau** [comment]
We just published 1.2.2, that should it. Sorry about the confusion

**Comment by charlatan154** [comment]
Yeh that worked. Thanks!
