### ISSUE TITLE
Introduction to ember-responsive at Global Ember meetup

### ISSUE THREAD

**Issue by taras** [freshbooks/ember-responsive#49]
Hi @f3ndot  and @alexBaizeau,

Would you like to give an introduction to ember-responsive lightning talk at Global Ember Meetup? 

It's a 15-20 minute talk that covers 
* Why it was created?
* When should it be used?
* What does the user need to be aware of?

And we'll make you a nice video like these https://vimeo.com/album/3607049

We have an [Ember Components Day coming up on December 5th](https://www.bigmarker.com/global-ember-meetup/Ember-Components-Day). This lightning talk would be a great fit there.

What do you think?

**Comment by alexBaizeau** [comment]
Hey Taras,

That sounds like à great idea!

**Comment by taras** [comment]
@alexBaizeau should I add you to the list of speakers?

**Comment by alexBaizeau** [comment]
:+1:
