### ISSUE TITLE
Question on testing

### ISSUE THREAD

**Issue by Jordan4jc** [freshbooks/ember-responsive#50]
Will this addon help me write tests to test responsive conditions being met?

I have an app I'm developing that we want people to run on their devices, so on the desktop using media queries it will show a message in place of the app to tell the user to open on their device. This works but I wanted to make a test for it to save my behind if I accidentally remove the class of override it somewhere.

Is there a way possibly with this addon that I can spoof a certain media query to then check if the proper message is being shown? And vise versa for the app to be shown on certain media queries?

**Comment by mitchlloyd** [comment]
Hypothetically you should be able to stub the media service in your tests to respond to your media queries. The ergonomics of this have changed over time and the last thing that worked for me was this:

```javascript
this.application.__deprecatedInstance__.register('service:foo', Ember.Service.extend());
```

I know that Robert Jackson has been working on the various testing libraries and registry implementations to improve this, so there might already be a better way.

**Comment by bantic** [comment]
The [Grand Testing Unification](https://github.com/emberjs/rfcs/pull/119) ember RFC has some good context on what works today and what the coming changes are, for mocking a service like ember-responsive in ember tests.

**Comment by k-fish** [comment]
There are now test helpers which spoof breakpoints. See linked PR.
