### ISSUE TITLE
Support FastBoot

### ISSUE THREAD

**Issue by tomdale** [freshbooks/ember-responsive#55]
I'm working on adding FastBoot to an app right now that relies on `ember-responsive`. Currently, including the addon causes apps to fail in FastBoot because it tries to detect the breakpoints on `init()`.

I was going to just fix the issue myself, but then I got to thinking: what is the correct behavior for `ember-responsive` when running on the server? There's no viewport so I'm unsure what the default viewport should be. Maybe user configurable?

**Comment by alexBaizeau** [comment]
Hey Tom,
I've never thought about this. 
A configurable breakpoint might be the best behaviour. We could also pick one if none is configurable.
I've never tried it but I believed that the the media query matcher will kick in when the generated dom is rendered on the client side and trigger a refresh of ember responsive.

**Comment by dtetto** [comment]
Setting a simulated viewport would eventually want to support to provide the growing list of media-queryable features (`device-aspect-ratio`, etc). I’d propose setting a hash for each of the queries:
`{ isMobile: true, isTablet: true, isDesktop: false }` as the states are not mutually exclusive. Default would be every query as `false`, as that‘d be the best practice to mirror your CSS — i.e. all media queries are special case code.

**Comment by alexBaizeau** [comment]
Thanks guys. it has been addressed  https://github.com/freshbooks/ember-responsive/pull/56. -- Never match anything.

**Comment by alexBaizeau** [comment]
I also cut v1.2.4.
