### ISSUE TITLE
1.2.4 Failed to create an instance of 'breakpoints:main'.

### ISSUE THREAD

**Issue by jeremytm** [freshbooks/ember-responsive#58]
I just tried the new 1.2.4 version (upgrading from 1.2.3), and I get the following error during init. Seems it doesn't play well with Ember Simple Auth (1.0.1)? Or am I doing something wrong?

Works fine in 1.2.3.

    Uncaught Error: Failed to create an instance of 'breakpoints:main'. Most likely an improperly defined class or an invalid module export.
    instantiate @ ember.debug.js:1453
    lookup @ ember.debug.js:1328
    Container.lookup @ ember.debug.js:1271
    lookup @ fake-owner.js:48
    (anonymous function) @ media.js:124
    ComputedPropertyPrototype.get @ ember.debug.js:14425
    get @ ember.debug.js:19745
    exports.default._emberMetalMixin.Mixin.create.get @ ember.debug.js:33962
    init @ media.js:111
    Class @ ember.debug.js:35385
    ClassMixinProps.create @ ember.debug.js:35663
    instantiate @ ember.debug.js:1470
    lookup @ ember.debug.js:1328
    buildInjections @ ember.debug.js:1367
    injectionsFor @ ember.debug.js:1425
    factoryFor @ ember.debug.js:1399
    instantiate @ ember.debug.js:1444
    lookup @ ember.debug.js:1328
    Container.lookup @ ember.debug.js:1271
    (anonymous function) @ ember.debug.js:32014
    exports.default @ lookup.js:6
    setupSessionRestoration @ setup-session-restoration.js:7
    initialize @ ember-simple-auth.js:5
    (anonymous function) @ ember.debug.js:4482
    (anonymous function) @ ember.debug.js:4498
    visit @ ember.debug.js:54796
    DAG.topsort @ ember.debug.js:2325
    _emberRuntimeSystemNamespace.default.extend._runInitializer @ ember.debug.js:4497
    _emberRuntimeSystemNamespace.default.extend.runInstanceInitializers @ ember.debug.js:4480
    _emberRuntimeSystemObject.default.extend._bootSync @ ember.debug.js:3545
    _emberRuntimeSystemNamespace.default.extend.didBecomeReady @ ember.debug.js:4517
    Queue.invoke @ ember.debug.js:320
    Queue.flush @ ember.debug.js:384
    DeferredActionQueues.flush @ ember.debug.js:185
    Backburner.end @ ember.debug.js:563
    Backburner.run @ ember.debug.js:685
    Backburner.join @ ember.debug.js:705
    run.join @ ember.debug.js:20147
    (anonymous function) @ ember.debug.js:20210
    fire @ jquery.js:3099
    self.fireWith @ jquery.js:3211
    jQuery.extend.ready @ jquery.js:3417
    completed @ jquery.js:3433

**Comment by alexBaizeau** [comment]
Sorry about that, thanks for reporting!

**Comment by alexBaizeau** [comment]
It should be fixed now on v1.2.5

**Comment by jeremytm** [comment]
Confirmed. Thanks for the speedy fix!
