### ISSUE TITLE
Testing not working as I would expect

### ISSUE THREAD

**Issue by anthonycollini** [freshbooks/ember-responsive#68]
I'm not sure if I am using the addon correctly, because it doesn't seem to be working in integration tests. 

I have added the following in my integration test:

`import { setBreakpointForIntegrationTest } from 'my-proper-app-name/tests/helpers/responsive';`
...

```
    test('shows the proper links on mobile', function(assert) {
      setBreakpointForIntegrationTest(this, 'mobile');
      this.render(hbs`{{header-user media=media}}`);

      this.$('navbar-toggle').click();
      assert.equal(this.$().find('.homepage-nav a:contains(Courses)').is(':visible'), true);
    });
```
I have a bootstrap nav that hides content at the mobile breakpoint and puts it into the mobile nav that requires clicking on the hamburger icon to open.

Does this add-on manipulate the browser size in the test, or are you required to use the conditionals provided by this add-on for the above code to work?

As of right now, it doesn't seem to properly assert that it is hidden on mobile, and when I `stop()` the test, I can see it is rendering the desktop view.

**Comment by alexBaizeau** [comment]
Hi,

The test helper will help you drive the conditionals provided by this addon.  in your particular example, `media.isMobile` will be true.

If you are using plain media queries - like bootstrap does - to make the navbar responsive, the test helper won't be able to force the navigation to behave like if it is rendered on a  mobile.

**Comment by cmccand** [comment]
Hi, I'm getting an error in acceptance test when I try to use setBreakpoint:  'setBreakpoint is not defined'. Anyone else encountered this? Not sure if there's something I'm doing wrong. Thanks!

**Comment by k-fish** [comment]
@cmccand if you've run `ember install ember-responsive` the test helper should have been generated `tests/helpers/responsive`. If you haven't or you have and it still isn't there, try running `ember generate ember-responsive`.

If you're still having trouble, create a new issue.
