### ISSUE TITLE
Usage within component on window resize

### ISSUE THREAD

**Issue by therealbenhogan** [freshbooks/ember-responsive#69]
Hi,

I am trying to use the add on within a component (using the didRender hook) but I can't monitor viewport size changes within that function. I've tried using a computed property but to no avail. Any help much appreciated!

**Comment by k-fish** [comment]
How are you trying to use the addon? Is the media service returning incorrect breakpoints?

**Comment by k-fish** [comment]
Closing due to lack of response.
