### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by noslouch** [freshbooks/ember-responsive#71]
064c167e845ea07c0eb3cf8cecf87fbe8abd37d0 doesn't seem to be included when I run `ember install ember-responsive` in my repo. I'm seeing it added to `package.json` at `1.2.5`. Not sure why this would happen, I'm looking at it with a fresh project now to see if it replicates.

**Comment by alexBaizeau** [comment]
Thank's for the heads up! I just published 1.2.7!

**Comment by jkeen** [comment]
Thanks @alexBaizeau!
