### ISSUE TITLE
Tag and push a new release to NPM?

### ISSUE THREAD

**Issue by jkeen** [freshbooks/ember-responsive#72]
Hey @alexBaizeau

The latest version of this addon (`1.2.6`) doesn't seemed to contain [this commit](https://github.com/freshbooks/ember-responsive/commit/064c167e845ea07c0eb3cf8cecf87fbe8abd37d0), which fixes an error that floods the console in the test environment complaining about "calling set on destroyed object".

Can you tag and push a new version up to NPM? I think this is what #71 is referring to, so you could close out two issues with one push. 💯 🚀

**Comment by alexBaizeau** [comment]
Hey @jkeen Thanks a lot for the reminder, I had a pretty busy week. I just published 1.2.7! 

Happy Friday!
