### ISSUE TITLE
v1.2.9 was a SemVer breaking change

### ISSUE THREAD

**Issue by kellyselden** [freshbooks/ember-responsive#81]
Anyone with `"ember-responsive": "^1.0.0"` in their `package.json` will start breaking the next time they run `npm install`. Was this intentional? I would advise rolling back your initializer changes and releasing `v1.2.10`. Then release `v2.0.0` with the breaking initializer changes.

**Comment by k-fish** [comment]
It wasn't intentional, I normally don't use carets, for stability, so it didn't occur to me. Thanks! I'll roll this out today.

**Comment by kellyselden** [comment]
Thank you!
