### ISSUE TITLE
{{media}} in template.hbs is undefined if I use media: Ember.inject.service() in route. Why?

### ISSUE THREAD

**Issue by johnunclesam** [freshbooks/ember-responsive#94]
`{{media}}` in **templates/route.hbs** is `undefined` if I use `media: Ember.inject.service()` in **routes/route.js**.

If instead I recreate the default `initializers/responsive.js` file everything works.

In route it works also with service inject only using this code in 

```javascript
activate() {
  console.log(this.get('media.isMobile'));
}
```

it logs `true` or `false` accordingly.

But in **template.hbs** this code: `{{log media}}` or `{{log media.classNames}}` or

```
{{#if media.isDesktop}}
  Desktop view!
{{/if}}
```

is always `undefined` or shows nothing until I use initializer instead of just inject service in this route only.

**Why?**

**Comment by k-fish** [comment]
Template use properties (like those from an injected service) from the controller, not the route. If you inject the media property inside the controller you will find it exists on the template.
