### ISSUE TITLE
Media classes not injecting during Acceptance Tests

### ISSUE THREAD

**Issue by tiandavis** [freshbooks/ember-responsive#95]
Hi Folks, thanks for putting together ember-responsive. Initially, I had similar expectations as the developer in https://github.com/freshbooks/ember-responsive/issues/93, but it makes sense that the acceptance helper wouldn't change the browser size because the addon itself doesn't change the browser size. But I think I'm running into another issue while analyzing how we can bring the responsive pieces under test.

My issue is the `media-*` classes don't seem to inject during the acceptance test runs.

![image](https://cloud.githubusercontent.com/assets/376230/25461265/f8c05cb2-2ab5-11e7-8192-616678d675cc.png)

So even if I pause the acceptance test and manually resize the browser, no responsive changes take place because there are no `media-*` classes to adjust on.

![image](https://cloud.githubusercontent.com/assets/376230/25461298/2bc305ba-2ab6-11e7-8540-fa28af1ad494.png)

Do we have to do anything with `tests/helpers/responsive.js` to get the injections working that I missed? 

Thanks Everyone!

**Comment by k-fish** [comment]
Hey @tiandavis 

The responsive acceptance helper doesn't set media matches with `setBreakpoint`, [it only mocks the is* properties on the media service](https://github.com/freshbooks/ember-responsive/blob/master/blueprints/ember-responsive/files/tests/helpers/responsive.js#L27)

If you want media class names to appear, there are a few ways you can add them, such as modifying the `setBreakpoint` helper function (in the responsive helper) to set your breakpoint with the matches array, which should update the `classNames` computed property. 

What you are trying to test?

**Comment by tiandavis** [comment]
Hi @k-fish! 👋

We're on a push to retrofit a mobile responsive UI/UX onto an existing desktop ember application.
![image](https://cloud.githubusercontent.com/assets/376230/25494582/1228687e-2b48-11e7-9395-5cecc21271da.png)


Using ember-responsive, we've made some initial progress so far.
![image](https://cloud.githubusercontent.com/assets/376230/25492924/87783ec0-2b42-11e7-875b-52d9393ecfb1.png)

Injecting the media-* classes helps us avoid using more media queries than we need.
![image](https://cloud.githubusercontent.com/assets/376230/25493071/fbb8b06c-2b42-11e7-8c33-c0b8482ec610.png)

Our acceptance test suite is mature and it would be awesome if we can run those same tests against a mobile form factor (even if it's just a desktop browser resized). Obviously, this is challenging because web browsers disable window.resizeTo and window.resizeBy APIs. So it is not practical to programmatically resize a web browser during tests.

I'm able to update ./testem.js to resize, at-least, Chrome during an `ember test -s` run.
```
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ],

  "browser_args": {
    "Chrome": [
      "--window-size=320,600"
    ]
  }
};
```

So my thought is if we can get the media class names to appear during acceptance tests, then we may have a shot at getting the responsive form factor itself under test.

![image](https://cloud.githubusercontent.com/assets/376230/25493618/cd0ffa84-2b44-11e7-9f81-2ede1cb59b0c.png)

I believe we're looking at the relevant piece of ./tests/helpers/responsive.js now:
```
MediaService.reopen({
  ...

  _forceSetBreakpoint(breakpoint) {
    let found = false;

    const props = {};
    this.get('_breakpointArr').forEach(function(bp) {
      const val = bp === breakpoint;
      if (val) {
        found = true;
      }

      props[`is${classify(bp)}`] = val;
    });

    if (found) {
      this.setProperties(props);
    } else {
      throw new Error(
        `You tried to set the breakpoint to ${breakpoint}, which is not in your app/breakpoint.js file.`
      );
    }
  },

  match() {}, // do not set up listeners in test

  ...

});

...
```
How should we modify `_forceSetBreakpoint` to get media class names to appear during acceptance tests?

Thanks a bunch!

**Comment by k-fish** [comment]
I can see at least two options you can try.

1. If you are fine with modifying the browser size in your `./testem.js`, you can actually get away with not using the breakpoint helper at all, as it only currently allows you to check the change in responsiveness (switching between breakpoints). Remove the response helper import in `start-app.js`, which will mean the media service doesn't get reopened for every test. 
Then you'll notice `classNames` will appear based on your browser size.

2. If you still want to be able to manipulate the breakpoint for specific tests, you'll have to modify your responsive helper and put a line in to set matches.
You'll have to be careful that you reset changes between tests though. 
Note: untested 😆 
```js
      const val = bp === breakpoint;
      if (val) {
        found = true;
        this.get('matches').push(bp);
      }
```

Let me know if you need clarification

**Comment by tiandavis** [comment]
BOOM! Validated both Option 1 and Option 2 gives us something to work with.

![image](https://cloud.githubusercontent.com/assets/376230/25499140/8745f076-2b58-11e7-8740-77bee4402c66.png)

Thanks for the help here @k-fish !

🎉

**Comment by k-fish** [comment]
Awesome! Going to close for now. Re-open if you have more questions
